import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { type Genre, type Story, generateStory } from "@/lib/storyTemplates";
import { BookOpen, Download, Feather, RefreshCw, Sparkles } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";

const genres: { id: Genre; emoji: string; label: string }[] = [
  { id: "fairy-tale", emoji: "\uD83E\uDDDA", label: "Fairy Tale" },
  { id: "horror", emoji: "\uD83D\uDC7B", label: "Horror" },
  { id: "adventure", emoji: "\uD83D\uDDFA\uFE0F", label: "Adventure" },
  { id: "mystery", emoji: "\uD83D\uDD0D", label: "Mystery" },
];

export default function App() {
  const [selectedGenre, setSelectedGenre] = useState<Genre | null>(null);
  const [characterName, setCharacterName] = useState("");
  const [story, setStory] = useState<Story | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  function handleGenerate() {
    if (!selectedGenre || !characterName.trim()) return;
    setIsGenerating(true);
    setTimeout(() => {
      setStory(generateStory(selectedGenre, characterName.trim()));
      setIsGenerating(false);
    }, 800);
  }

  function handleNewStory() {
    setStory(null);
    setSelectedGenre(null);
    setCharacterName("");
  }

  function handleDownloadPDF() {
    window.print();
  }

  const canGenerate = selectedGenre !== null && characterName.trim().length > 0;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Hidden print-only area */}
      <div id="print-area" aria-hidden="true">
        {story && (
          <>
            <h2>{story.title}</h2>
            {story.paragraphs.map((p) => (
              <p key={p.slice(0, 40)}>{p}</p>
            ))}
            <p style={{ marginTop: 32, fontSize: 12, color: "#6B7280" }}>
              Generated by NarrativeForge
            </p>
          </>
        )}
      </div>

      {/* Navigation */}
      <header className="sticky top-0 z-50 bg-card shadow-nav border-b border-border">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-teal flex items-center justify-center">
              <Feather className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-foreground text-lg tracking-tight">
              NarrativeForge
            </span>
          </div>

          <nav className="hidden md:flex items-center gap-6">
            {["Home", "How It Works", "Pricing", "Templates", "My Stories"].map(
              (item) => (
                <a
                  key={item}
                  href="/"
                  className={`text-sm font-medium transition-colors ${
                    item === "Home"
                      ? "text-teal"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                  data-ocid="nav.link"
                >
                  {item}
                </a>
              ),
            )}
          </nav>

          <Button
            className="bg-teal hover:bg-teal-dark text-white text-sm font-semibold hidden md:flex"
            data-ocid="nav.primary_button"
          >
            Sign Up Free
          </Button>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero */}
        <section className="pt-16 pb-12 px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 bg-teal/10 text-teal text-xs font-semibold px-3 py-1.5 rounded-full mb-6">
              <Sparkles className="w-3.5 h-3.5" />
              AI-Powered Story Generation
            </div>
            <h1 className="text-4xl sm:text-5xl font-extrabold text-foreground leading-tight mb-4 max-w-2xl mx-auto">
              Your Imagination,{" "}
              <span
                style={{
                  background: "linear-gradient(90deg, #2FA7A1, #3BB2A8)",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                }}
              >
                Amplified.
              </span>
              <br />
              Create Unique Stories in Seconds.
            </h1>
            <p className="text-muted-foreground text-base sm:text-lg max-w-xl mx-auto">
              Choose your genre, name your hero, and watch a hand-crafted story
              unfold &mdash; ready to read, share, or download.
            </p>
          </motion.div>
        </section>

        {/* Generator / Output */}
        <AnimatePresence mode="wait">
          {!story ? (
            <motion.section
              key="generator"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.4 }}
              className="px-6 pb-16 flex justify-center"
            >
              <div
                className="bg-card rounded-2xl shadow-card w-full max-w-xl p-8"
                data-ocid="story.card"
              >
                {/* Genre */}
                <div className="mb-6">
                  <p className="text-sm font-semibold text-foreground mb-3">
                    1. Choose your genre
                  </p>
                  <div className="grid grid-cols-4 gap-3">
                    {genres.map((g) => (
                      <button
                        type="button"
                        key={g.id}
                        onClick={() => setSelectedGenre(g.id)}
                        data-ocid="story.tab"
                        className={`flex flex-col items-center gap-1.5 p-3 rounded-xl border-2 transition-all text-center ${
                          selectedGenre === g.id
                            ? "bg-teal border-teal text-white"
                            : "bg-surface border-border text-foreground hover:border-teal/40"
                        }`}
                      >
                        <span className="text-xl">{g.emoji}</span>
                        <span className="text-xs font-semibold leading-tight">
                          {g.label}
                        </span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Name */}
                <div className="mb-6">
                  <p className="text-sm font-semibold text-foreground mb-3">
                    2. Name your character
                  </p>
                  <Input
                    placeholder="Enter character name..."
                    value={characterName}
                    onChange={(e) => setCharacterName(e.target.value)}
                    onKeyDown={(e) =>
                      e.key === "Enter" && canGenerate && handleGenerate()
                    }
                    className="h-11 rounded-xl border-border focus-visible:ring-teal/40"
                    data-ocid="story.input"
                  />
                </div>

                {/* Generate */}
                <button
                  type="button"
                  onClick={handleGenerate}
                  disabled={!canGenerate || isGenerating}
                  data-ocid="story.submit_button"
                  className="w-full h-12 rounded-xl text-white font-semibold text-base transition-all disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  style={{
                    background: "linear-gradient(90deg, #2FA7A1, #3BB2A8)",
                  }}
                >
                  {isGenerating ? (
                    <>
                      <svg
                        className="animate-spin w-4 h-4"
                        fill="none"
                        viewBox="0 0 24 24"
                        aria-label="Loading"
                        role="img"
                      >
                        <title>Loading</title>
                        <circle
                          className="opacity-25"
                          cx="12"
                          cy="12"
                          r="10"
                          stroke="currentColor"
                          strokeWidth="4"
                        />
                        <path
                          className="opacity-75"
                          fill="currentColor"
                          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                        />
                      </svg>
                      Crafting your story...
                    </>
                  ) : (
                    "Generate My Story \u2192"
                  )}
                </button>
              </div>
            </motion.section>
          ) : (
            <motion.section
              key="output"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.45 }}
              className="px-6 pb-16"
            >
              <div className="max-w-5xl mx-auto">
                <h2 className="text-2xl font-bold text-foreground mb-6">
                  Story Output
                </h2>
                <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-6">
                  {/* Story card */}
                  <div
                    className="bg-card rounded-2xl shadow-card p-8"
                    data-ocid="story.panel"
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <BookOpen className="w-4 h-4 text-teal" />
                      <span className="text-xs font-semibold text-teal uppercase tracking-wider">
                        {genres.find((g) => g.id === selectedGenre)?.label}
                      </span>
                    </div>
                    <h3 className="text-2xl font-bold text-foreground mb-6">
                      {story.title}
                    </h3>
                    <div className="space-y-4">
                      {story.paragraphs.map((p) => (
                        <p
                          key={p.slice(0, 40)}
                          className="text-foreground/80 leading-relaxed text-[15px]"
                        >
                          {p}
                        </p>
                      ))}
                    </div>
                  </div>

                  {/* Sidebar */}
                  <div
                    className="flex flex-col gap-4"
                    data-ocid="story.section"
                  >
                    <div className="bg-card rounded-2xl shadow-card p-6">
                      <p className="text-sm font-semibold text-foreground mb-4">
                        Story Options
                      </p>
                      <div className="flex flex-col gap-3">
                        <button
                          type="button"
                          onClick={handleNewStory}
                          data-ocid="story.secondary_button"
                          className="w-full h-11 rounded-xl bg-surface border border-border text-foreground font-semibold text-sm hover:bg-border/40 transition-colors flex items-center justify-center gap-2"
                        >
                          <RefreshCw className="w-4 h-4" />
                          New Story
                        </button>
                        <button
                          type="button"
                          onClick={handleDownloadPDF}
                          data-ocid="story.primary_button"
                          className="w-full h-11 rounded-xl text-white font-semibold text-sm flex items-center justify-center gap-2"
                          style={{
                            background:
                              "linear-gradient(90deg, #2FA7A1, #3BB2A8)",
                          }}
                        >
                          <Download className="w-4 h-4" />
                          Download as PDF
                        </button>
                      </div>
                    </div>

                    {/* Story details */}
                    <div className="bg-teal/5 border border-teal/20 rounded-2xl p-5">
                      <p className="text-xs font-semibold text-teal mb-3">
                        Story Details
                      </p>
                      <div className="space-y-2 text-xs text-muted-foreground">
                        <div className="flex justify-between">
                          <span>Genre</span>
                          <span className="font-medium text-foreground">
                            {genres.find((g) => g.id === selectedGenre)?.label}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span>Character</span>
                          <span className="font-medium text-foreground">
                            {characterName}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span>Paragraphs</span>
                          <span className="font-medium text-foreground">
                            {story.paragraphs.length}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span>~Words</span>
                          <span className="font-medium text-foreground">
                            {story.paragraphs.join(" ").split(" ").length}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="bg-surface border-t border-border py-6 px-6">
        <div className="max-w-6xl mx-auto text-center text-sm text-muted-foreground">
          &copy; {new Date().getFullYear()}. Built with{" "}
          <span className="text-red-400">&hearts;</span> using{" "}
          <a
            href={`https://caffeine.ai?utm_source=caffeine-footer&utm_medium=referral&utm_content=${encodeURIComponent(
              typeof window !== "undefined" ? window.location.hostname : "",
            )}`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-teal hover:underline font-medium"
          >
            caffeine.ai
          </a>
        </div>
      </footer>
    </div>
  );
}
